### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by barrynorman** [brianzinn/babylonjs-hook#3]
Good Evening,

I followed the documentation and I tried many different things, but I was not successfull...
I can run and build my react app, but I can not test it. 

Jest is complaining about 
`import SceneComponent from 'babylonjs-hook';`

Any ideas?

**Comment by brianzinn** [comment]
I don't know how your test environment is configured, but it's not setup for import statements.
Does this help?
`https://github.com/facebook/jest/issues/9395`

**Comment by brianzinn** [comment]
closing as this is a stale issue, but please re-open if above did not solve for you.  cheers.
