### ISSUE TITLE
[BUG] Can't resolve '@babylonjs/core/Engines/engine'

### ISSUE THREAD

**Issue by Alecell** [brianzinn/babylonjs-hook#4]
I was trying to use the module, but when I run it shows this error:
![image](https://user-images.githubusercontent.com/13935760/130718793-a1aded75-ac3c-406a-b167-ee4879bc835f.png)

The error don't show if I use the `react-babylonjs` with the (almost) same code.

**Comment by brianzinn** [comment]
Are you on webpack 5?

**Comment by Alecell** [comment]
Yes, I'm. That's the issue?

**Comment by brianzinn** [comment]
I’ll fix it and put out a new release tomorrow.

**Comment by brianzinn** [comment]
hi @Alecell can you give the new version a try v `0.0.10`?

**Comment by brianzinn** [comment]
closing as it should be fixed - please re-open if not.  cheers.
