### ISSUE TITLE
How to use multiple scenes and switch between them?

### ISSUE THREAD

**Issue by sabinayakc** [brianzinn/babylonjs-hook#6]
Hello,

Suppose I have two scenes - Menu Scene and Game Scene.

How do you recommend using this hook to manage multiple scenes?

**Comment by brianzinn** [comment]
I would start by saying that is not supported in an elegant way, but will try to offer some solutions.

You could do it by loading another scene entirely.  Here is a demo that uses `react-babylonjs`, but the principle is the same [/react-babylonjs/examples/basic/toggle-scene/](https://brianzinn.github.io/react-babylonjs/examples/basic/toggle-scene/).  This will create a new engine completely.

Load a new scene when your game state changes:
```jsx
const [gameState, setGameState] = useState('menu');
{(gameState === 'menu') &&
  <Scene onSceneMount={loadMenu} />
}
{(gameState === 'game') &&
  <Scene onSceneMount={loadGame} />
}
```
It may be better to just show the menu on top of the game, if you use full screen.  You can always pause/hide the actual game.

You could also render a different scene in your onRender method.  That won't work with this package.  You will need to maintain references to 2 scenes.  Essentially you would do this:
```typescript
engine.runRenderLoop(() => {
  if(state.value === 'menu') {
    menuScene.render();
  } else {
    gameScene.render();
  }
})
```
Benefit of that over creating new scenes is the 2 scenes are always loaded, so you can switch immediately and maintain state easier across the scenes.  I think the best solution still is to load menu on top and have a more dynamic scene, but may not work for your game.  I do somewhat support that in `react-babylonjs`, but I have never tried.  You can load 2 scenes in an Engine:
```jsx
/** if you remove the cameras from a scene - it will not render **/
<Engine ...>
  <Scene />
  <Scene />
</Engine>
```

**Comment by sabinayakc** [comment]
Thank you for the reply. Will try these out. Going to start with a simpler route with your suggestion and show/hide menu. 

Appreciate all the work you do!
